# Exercise 3.17: Modify Example 3.24 to add another classifier to the
# ensemble learning, for example, K-nearest neighbor.
from sklearn import datasets
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

iris = datasets.load_iris()
X, y = iris.data[:, 1:3], iris.target

clf1 = LogisticRegression(random_state=1)
clf2 = RandomForestClassifier(n_estimators=50, random_state=1)
clf3 = GaussianNB()
clf4 = SVC()
clf5 = KNeighborsClassifier()

eclf = VotingClassifier(
     estimators=[('lr', clf1), ('rf', clf2), ('gnb', clf3), ('svc', clf4), ('knn', clf5)],
     voting='hard')

for clf, label in zip([clf1, clf2, clf3, clf4, clf5, eclf],
                       ['Logistic Regression', 'Random Forest', 'naive Bayes', 'SVM', 'KNN', 'Ensemble']):
     scores = cross_val_score(clf, X, y, scoring='accuracy', cv=5)
     print("Accuracy: %0.2f (+/-%0.2f) [%s]" % (scores.mean(), scores.std(), label))
